name: flutter_todo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.5.0
#  leancloud_storage: ^0.7.10
  cached_network_image: ^3.4.1
  universal_platform: ^1.1.0
  fluro: ^2.0.3 #路由
#  image_picker: ^0.6.1+10
#  url_launcher: ^6.0.10
#  url_launcher_web: 2.0.6
#  url_strategy: ^0.2.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  after_layout:
  provider: ^6.1.2
  lint: ^2.3.0
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  fl_chart: ^0.70.2
  win32: ^5.0.0
  domain:
    path: packages/domain
  data:
    path: packages/data
  shared:
    path: packages/shared
  widgets:
    path: packages/widgets
  resources:
    path: packages/resources

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  intl: ^0.19.0
  intl_utils: ^2.8.6

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  output_dir: lib/language/generated
  arb_dir: lib/language/l10n

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/tabs/
    - assets/file/
    - assets/images/

#  fonts:
#    - family: XiaoWei
#      fonts:
#        - asset: assets/fonts/XiaoWei-Regular.ttf















