name: flutter_todo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  leancloud_storage: ^0.7.8
  cached_network_image: ^3.2.0
  universal_platform: ^1.0.0+1
  fluro: ^2.0.3 #路由
#  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/tabs/

#  fonts:
#    - family: XiaoWei
#      fonts:
#        - asset: assets/fonts/XiaoWei-Regular.ttf















