name: flutter_todo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  leancloud_storage: ^0.7.8
  cached_network_image: ^3.2.0
  universal_platform: ^1.0.0+1
  fluro: ^2.0.3 #路由
#  image_picker: ^0.6.1+10
  url_launcher: ^6.0.10
  url_launcher_web: 2.0.6
  url_strategy: ^0.2.0
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1
#  chat_gpt_sdk: ^1.0.2+4
  after_layout:
  provider: ^6.1.2
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  intl: ^0.17.0
  intl_utils: ^2.4.0

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  output_dir: lib/language/generated
  arb_dir: lib/language/l10n

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/tabs/
    - assets/file/
    - assets/images/

#  fonts:
#    - family: XiaoWei
#      fonts:
#        - asset: assets/fonts/XiaoWei-Regular.ttf















